# Generated by Django 6.0.7 on 2026-07-16 23:58

import campaigns.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('tagline', models.CharField(blank=True, default='', max_length=160)),
                ('description', models.TextField(max_length=8000)),
                ('category', models.CharField(choices=[('education', 'Education'), ('medical', 'Medical'), ('community', 'Community'), ('emergency', 'Emergency'), ('creative', 'Creative'), ('nonprofit', 'Non-profit'), ('personal', 'Personal'), ('other', 'Other')], default='other', max_length=20)),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('qr_code', models.ImageField(upload_to=campaigns.models.qr_upload_path)),
                ('upi_id', models.CharField(blank=True, default='', max_length=80)),
                ('payee_name', models.CharField(blank=True, default='', max_length=80)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=campaigns.models.cover_upload_path)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='active', max_length=10)),
                ('show_amounts', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=12, unique=True)),
                ('donor_name', models.CharField(max_length=60)),
                ('donor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('message', models.CharField(blank=True, default='', max_length=280)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('transaction_ref', models.CharField(blank=True, default='', max_length=64)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to=campaigns.models.proof_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('review_note', models.CharField(blank=True, default='', max_length=200)),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('goal_amount__gt', 0)), name='campaign_goal_positive'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['campaign', 'status'], name='campaigns_d_campaig_6f1325_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['campaign', 'created_at'], name='campaigns_d_campaig_cd6778_idx'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='donation_amount_positive'),
        ),
    ]
