# Generated by Django 6.0.7 on 2026-07-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='qr_payload',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
