# Generated by Django 6.0.7 on 2026-07-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_qr_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payer_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
