# Generated by Django 6.0.7 on 2026-07-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_campaignimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="impact_action",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="campaign",
            name="impact_completed_action",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="campaign",
            name="impact_completed_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="campaign",
            name="impact_completed_qty",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="campaign",
            name="impact_conv_rupees",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="impact_conv_units",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="impact_default_view",
            field=models.CharField(
                choices=[("funds", "Funds"), ("impact", "Impact")],
                default="funds",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="impact_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="campaign",
            name="impact_expenses",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="campaign",
            name="impact_funds_basis",
            field=models.CharField(
                choices=[
                    ("eligible", "Eligible funds after expenses"),
                    ("all", "All verified funds"),
                    ("percent", "Percentage of verified funds"),
                ],
                default="all",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="impact_funds_percent",
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="campaign",
            name="impact_item",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="campaign",
            name="impact_manual_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="campaign",
            name="impact_mode",
            field=models.CharField(
                choices=[
                    ("auto", "Automatic from verified funds"),
                    ("manual", "Updated manually"),
                ],
                default="auto",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="impact_target",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="impact_unit",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="campaign",
            name="impact_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
