# Generated by Django 6.0.7 on 2026-07-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0007_fund_use_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="funduseimage",
            name="caption",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
    ]
