# Generated by Django 6.0.7 on 2026-07-21 03:36

import campaigns.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0008_fund_use_image_caption"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="qr_daily_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="qr_label",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.CreateModel(
            name="CampaignQR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=60)),
                ("image", models.ImageField(upload_to=campaigns.models.qr_upload_path)),
                (
                    "qr_payload",
                    models.TextField(blank=True, default="", max_length=1000),
                ),
                ("upi_id", models.CharField(blank=True, default="", max_length=80)),
                ("payee_name", models.CharField(blank=True, default="", max_length=80)),
                (
                    "daily_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_qrs",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddField(
            model_name="donation",
            name="qr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donations",
                to="campaigns.campaignqr",
            ),
        ),
    ]
